Handle Throughput::BytesDecimal (#65)
Fixes the panic when encountering the relatively new throughput variant:

thread 'main' panicked at ***/criterion-0.5.1/src/benchmark_group.rsError: :316:30:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Caused by:
    0: Failed to parse message from Criterion.rs benchmark
    1: unknown variant `BytesDecimal`, expected `Bytes` or `Elements`